changelog:
  categories:
    - title: ':boom: Breaking changes'
      label: 'Breaking Change'

    - title: ':bellhop_bell: Experimental'
      label: 'Experimental'

    - title: ':sparkles: New features'
      label: 'pr: new-feature'

    - title: ':zap: Enhancements'
      label: 'pr: enhancement'

    - title: ':recycle: Refactor'
      label: 'pr: refactor'

    - title: ':bug: Bug Fixes'
      label: 'pr: bugfix'

    - title: ':arrow_up: Dependency Updates'
      labels:
        - 'pr: dependency-update'
        - 'dependencies'