---
name: "hacs-bot"
description: You use this when hacs-bot did something wrong.
labels: "issue:bot"
body:
- type: textarea
  attributes:
    label: Describe the issue
    placeholder: "A clear and concise description of what the issue is."
  validations:
    required: true
