---
name: "HACS Action"
description: You use this when there is an issue with the HACS action.
labels: "issue:action"
body:
- type: textarea
  attributes:
    label: Describe the issue
    placeholder: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: input
  attributes:
    label: Link to action run
  validations:
    required: true
- type: input
  attributes:
    label: Link to action configuration
  validations:
    required: true
