---
name: "Issue: Documentation"
description: You use this when something is wrong with the documentation.
labels: "issue:documentation"
body:
- type: textarea
  attributes:
    label: Describe the issue
    placeholder: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    placeholder: "Here you paste screenshots to showcase the issue."
