default_config:
logger:
  default: error
  logs:
    custom_components.hacs: debug
    hacs: debug

frontend:
  themes: !include_dir_merge_named themes


hacs:
  token: CHANGE_ME
  appdaemon: true
  python_script: true
  theme: true
  dev: true