trigger:
  paths:
    include:
      - docs/*
      - "mkdocs.yml"
      - ".pipelines/documentation.yml"

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0
    displayName: 'Set 3.7.X as Python version'
    inputs:
      versionSpec: '3.7.x'

  - script: python3 -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'

  - script: "pip3 install ghp-import mkdocs pymdown-extensions"
    displayName: 'Install dependencies'

  - script: |
      git checkout gh-pages
      git reset --hard ROOT
      git push -f
    displayName: 'Clear current documentation'

  - script: |
      git checkout master
      sed -i "s|site_dir: site/next|site_dir: site|" mkdocs.yml
      python3 -m mkdocs build -c
    displayName: 'Generate documentation for master'

  - script: |
      git checkout next
      sed -i "s|site_dir: site|site_dir: site/next|" mkdocs.yml
      python3 -m mkdocs build
    displayName: 'Generate documentation for next'

  - script: |
      ghp-import site -p -b gh-pages -n -m 'Automagically publish documentation'
    displayName: 'Publish documentation'