name: Codecov

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: make init

    - name: Generate coverage report
      env:
        PYTEST: true
      run: |
        pip install pytest
        pip install pytest-cov
        python3 -m pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}