name: Codecov

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:
    name: Codecov
    runs-on: ubuntu-latest
    container:
      image: hacscontainer/${{ matrix.version }}
      env:
        PYTEST: true
    strategy:
      matrix:
        version: ["python37", "python38", "python39"]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run:  make init

    - name: Generate coverage report
      run: |
        python3 -m pip install pytest pytest-cov
        python3 -m pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      if: ${{ matrix.version }} == "python38"
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
