name: "Cron action 17:00"

on:
  schedule:
    - cron:  '0 17 * * *'

jobs:
  cron:
    name: Sugest a new release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Enable version 3.7 of Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel
          python3 -m pip install -r /home/runner/work/integration/integration/requirements.txt

      - name: Create issue sugesting a new release
        run: python3 /home/runner/work/integration/integration/manage/generate_releasenotes.py --token ${{ secrets.GITHUB_TOKEN }} --release no