name: "HACS Actions"

on:
  issues:
    types: [labeled, opened, edited, milestoned]
  issue_comment:
    types: [created]


jobs:
  test:
    name: Automation
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/actions@master
        name: HACS Actions
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"