name: Home Assistant

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ha_test:
    name: Home Assistant Check
    container:
      image: hacscontainer/${{ matrix.version }}
    strategy:
      matrix:
        #version: ["python37", "python38", "python39"]
        version: ["python37", "python38"]
    runs-on: ubuntu-latest
    steps:
    - name: "Get the repository content"
      uses: actions/checkout@v2

    - name: Install dependencies
      run: make init

    - name: Install dependencies for custom_components
      run: |
        for file in $(find custom_components/ -name "manifest.json"); do
          cat "$file" | for req in $(jq .requirements[]);
            do pip install $(echo "$req" | jq -r .);
            done;
          done

    - name: 'Copy sample configuration for Home Assistant'
      run: cp -f .devcontainer/sample_configuration.yaml ./configuration.yaml

    - name: Home Assistant configuration check
      run: |
        echo "Testing with this configuration:"
        cat configuration.yaml
        echo ""
        hass --script check_config --config .