name: "Automation"

on: issues

jobs:
  test:
    name: Issue greeter
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/hacs-actions@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          action: "IssueGreeter"