name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: "Set version numbmer"
        run: |
          sed -i '/INTEGRATION_VERSION = /c\INTEGRATION_VERSION = "${{ github.ref }}"' /home/runner/work/integration/integration/custom_components/hacs/const.py
          sed -i 's|refs/heads/||' /home/runner/work/integration/integration/custom_components/hacs/const.py
          sed -i 's|refs/tags/||' /home/runner/work/integration/integration/custom_components/hacs/const.py

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP HACS Dir
        run: |
          cd /home/runner/work/integration/integration/custom_components/hacs
          zip hacs.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/integration/integration/custom_components/hacs/hacs.zip
          asset_name: hacs.zip
          tag: ${{ github.ref }}
          overwrite: true
