name: Prepare release

on:
  release:

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1


      # Get updated translations
      - name: Download Lokalise CLI
        run: |
          curl -sSL \
            "https://s3-eu-west-1.amazonaws.com/lokalise-assets/cli/lokalise-0.721-linux-amd64.tgz" \
            -o ./lokalise.tgz
          tar -xvzf ./lokalise.tgz
      - name: Downloading translations
        run: |
          ./lokalise \
              --token "${{ secrets.lokalise_token }}" \
              export "190570815d9461966ae081.06523141" \
              --type json \
              --unzip_to  /tmp/lokalise \
              --filter reviewed \
              --export_empty skip \
              --export_sort a_z
      - name: Clear current translations
        run: |
          rm custom_components/hacs/.translations/*
      - name: Move new  translations
        run: |
          cp /tmp/lokalise/locale/* custom_components/hacs/.translations/


      # Build Frontend
      - name: Build the HACS frontend
        run: npm install && npm run build


      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP HACS Dir
        run: "zip hacs.zip -r custom_components/hacs"
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hacs.zip
          asset_name: hacs.zip
          tag: ${{ github.ref }}
          overwrite: true